"""
    Phenixio API Reference

     # Introduction  The Phenixio API allows you to integrate Lightning Network payments into your application.  ## Just Getting Started?  Start developing your Phenixio integration with our client libraries. We will publish a guide soon: [Development Quickstart](https://github.com/phenixio/sdk)   ## Generating Access Token  API endpoints require token based authentication. You can [Generate Access Token](#post-/token/) with your user credentials. You will recieve an access token in JWT format. Set your request header \"Authorization: Bearer `<YOUR-ACCESS-TOKEN>`\"   ## Curl Example  Test your access token with Curl request. Replace `<YOUR-ACCESS-TOKEN>` with your actual token.   ```bash $ curl -I -X GET --http1.1 -H \"Content-Type: application/json\" -H \"Authorization: Bearer <YOUR-ACCESS-TOKEN>\"  https://sandbox.phenixio.com/api/charges/ ```     # noqa: E501

    The version of the OpenAPI document: v0.3.2-beta [testnet]
    Contact: support@phenixio.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import phenixio
from phenixio.api.payments_api import PaymentsApi  # noqa: E501


class TestPaymentsApi(unittest.TestCase):
    """PaymentsApi unit test stubs"""

    def setUp(self):
        self.api = PaymentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_payments_create(self):
        """Test case for payments_create

        New Payment Request  # noqa: E501
        """
        pass

    def test_payments_list(self):
        """Test case for payments_list

        Received Payments  # noqa: E501
        """
        pass

    def test_payments_pending_list(self):
        """Test case for payments_pending_list

        Pending Payments  # noqa: E501
        """
        pass

    def test_payments_read(self):
        """Test case for payments_read

        Payment Info  # noqa: E501
        """
        pass

    def test_payments_sum_read(self):
        """Test case for payments_sum_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
