"""
    Phenixio API Reference

     # Introduction  The Phenixio API allows you to integrate Lightning Network payments into your application.  ## Just Getting Started?  Start developing your Phenixio integration with our client libraries. We will publish a guide soon: [Development Quickstart](https://github.com/phenixio/sdk)   ## Generating Access Token  API endpoints require token based authentication. You can [Generate Access Token](#post-/token/) with your user credentials. You will recieve an access token in JWT format. Set your request header \"Authorization: Bearer `<YOUR-ACCESS-TOKEN>`\"   ## Curl Example  Test your access token with Curl request. Replace `<YOUR-ACCESS-TOKEN>` with your actual token.   ```bash $ curl -I -X GET --http1.1 -H \"Content-Type: application/json\" -H \"Authorization: Bearer <YOUR-ACCESS-TOKEN>\"  https://sandbox.phenixio.com/api/charges/ ```     # noqa: E501

    The version of the OpenAPI document: v0.4.2-beta [testnet]
    Contact: support@phenixio.com
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "phenixio"
VERSION = "0.1.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
  "urllib3 >= 1.25.3",
  "python-dateutil",
]

setup(
    name=NAME,
    version=VERSION,
    description="Phenixio API Reference",
    author="OpenAPI Generator community",
    author_email="support@phenixio.com",
    url="https://github.com/phenixio/phenixio-python",
    keywords=["OpenAPI", "OpenAPI-Generator", "Phenixio API Reference"],
    python_requires=">=3.6",
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description="""\
     # Introduction  The Phenixio API allows you to integrate Lightning Network payments into your application.  ## Just Getting Started?  Start developing your Phenixio integration with our client libraries. We will publish a guide soon: [Development Quickstart](https://github.com/phenixio/sdk)   ## Generating Access Token  API endpoints require token based authentication. You can [Generate Access Token](#post-/token/) with your user credentials. You will recieve an access token in JWT format. Set your request header \&quot;Authorization: Bearer &#x60;&lt;YOUR-ACCESS-TOKEN&gt;&#x60;\&quot;   ## Curl Example  Test your access token with Curl request. Replace &#x60;&lt;YOUR-ACCESS-TOKEN&gt;&#x60; with your actual token.   &#x60;&#x60;&#x60;bash $ curl -I -X GET --http1.1 -H \&quot;Content-Type: application/json\&quot; -H \&quot;Authorization: Bearer &lt;YOUR-ACCESS-TOKEN&gt;\&quot;  https://sandbox.phenixio.com/api/charges/ &#x60;&#x60;&#x60;     # noqa: E501
    """
)
